name: car_env
channels:
- conda-forge
- defaults
dependencies:
- jupyter
- imageio=2.19.3
- imageio-ffmpeg=0.4.7
- watermark=2.3.1
# General data science stuff
- fastprogress
- matplotlib=3.5.2
- numpy=1.21.5
- openpyxl=3.0.9
- pandas=1.4.2
- scipy=1.5.3
- scikit-learn==1.1.1
# PyMC dependencies
- blas
- mkl-service
# Pip and custom packages
- pip
- pip:
  - hagelkorn
  - calibr8==6.5.2
  - murefi==5.1.0
  # PyMC installs more reliably with pip
  # as long as important dependencies are installed with conda already
  - pymc==4.0.0
  - pyrff==2.0.2
